### ISSUE TITLE
Formatting inconsistency?

### ISSUE THREAD

**Issue by willeccles** [druskus20/hugo-site#1]
There's one music recommendation that is not italicized like the rest, is this intentional?

https://github.com/druskus20/hugo-site/blob/9a6d4147032eef448e98a10ef2fa43cf1edb3982/layouts/index.html#L63

**Comment by NaincyKumariKnoldus** [comment]
Hey @willeccles Can I do this please? Can I add that?

**Comment by druskus20** [comment]
> There's one music recommendation that is not italicized like the rest, is this intentional?
> 
> https://github.com/druskus20/hugo-site/blob/9a6d4147032eef448e98a10ef2fa43cf1edb3982/layouts/index.html#L63

Much thanks very hi.
